### ISSUE TITLE
Check if interface is deleted

### ISSUE THREAD

**Issue by tungates** [execriez/NetworkStatusWarden#1]
When disconnecting from the cisco anyconnect client NetworkStatusWarden doesn't detect that the interface has been deleted and therefore doesn't detect the change in the nstwork Status

When the anyconnect client connects to the vpn it creates the "com.cisco.anyconnect utun1" interface and then when you disconnect the com.cisco.anyconnect utun1 interface is deleted from the mac

**Comment by execriez** [comment]
Thanks for the feedback. I have updated the files on GitHub to hopefully address this. Please let me know if it works for you.

BTW:
When using Cisco AnyConnect to create a VPN connection, the following seems to be true (at least on my version):
For IPv4, the interface remains the same, but the service changes to "com.cisco.anyconnect"
For IPv6, the interface changes to utun0, and the service changes to "com.cisco.anyconnect"

You can see this because the SCutil records contain the following after you create a VPN connection

State,/Network/Global/IPv4,PrimaryInterface,en1
State,/Network/Global/IPv4,PrimaryService,com.cisco.anyconnect
State,/Network/Global/IPv6,PrimaryInterface,utun0
State,/Network/Global/IPv6,PrimaryService,com.cisco.anyconnect

NetworkStatusWarden doesn't currently support IPv6.

**Comment by tungates** [comment]
Hi,

Just letting you know that all is good with the changes made. Thanks heaps
for this.

Regards
Shane
